all:
	arm-linux-gnueabi-gcc -g -o test1 test1.c
	arm-linux-gnueabi-gcc -g -o test2 test2.c
	arm-linux-gnueabi-gcc -g -o test3 test3.c
	arm-linux-gnueabi-gcc -g -o test4 test4.c
	arm-linux-gnueabi-gcc -g -o test5 test5.c
	arm-linux-gnueabi-gcc -g -o test6 test6.c
	arm-linux-gnueabi-gcc -g -o test7 test7.c
	arm-linux-gnueabi-gcc -g -o test8 test8.c
