all:
	arm-linux-gnueabi-gcc -g -o server1 server1.c
	arm-linux-gnueabi-gcc -g -o server2 server2.c
	arm-linux-gnueabi-gcc -g -o server3 server3.c
	arm-linux-gnueabi-gcc -g -o server4 server4.c
	arm-linux-gnueabi-gcc -g -o server5 server5.c
